exclude: opcodes.py
repos:
  - repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify
        args:
          - --quote
          - '"'
          - --in-place
        language: python
        types:
          - python
  # - repo: https://github.com/pre-commit/mirrors-yapf
  #   rev: v0.32.0
  #   hooks:
  #     - id: yapf
  #       additional_dependencies:
  #         - toml
  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v5.10.1
  #   hooks:
  #     - id: isort
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline
